logging:
  level:
    org.springframework.web: DEBUG
    root: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem:demodb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
server:
  port: 8081